version: '3.9'
services:
  mysql:
    container_name: mysql_container_bigOh
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=sachin
      - MYSQL_DATABASE=bigOh
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
    ports: 
      - '3306:3306'
    volumes: 
      - ./docker-volumes/mysql:/var/lib/mysql